// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DTOGenerator2
{
    internal sealed partial class Vsix
    {
        public const string Id = "DTOGenerator.9948887e-7866-4600-b00a-5bedec1ad633";
        public const string Name = "DTOGenerator";
        public const string Description = @"Easily generate DTO (Data Transfer Object) classes for your entities and save them to your desired folder. Simply right-click the folder containing your entities, select 'Generate DTOs' and choose the destination folder. It's that simple!";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mert BAYKAR";
        public const string Tags = "DTOTool;DTOGenerator;EntityDTO;EntityToDTO;AutoGenerateDTO;AutoDTO;ModelToDTO;CodeGeneration;ClassGeneration;EntityFramework;CSharp;CodeAutomation;DeveloperTools";
    }
}
