// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DTOGenerator2
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DTOGeneratorString = "f8810deb-4ff3-45a3-9fbe-d89bfcde5774";
        public static Guid DTOGenerator = new Guid(DTOGeneratorString);

        public const string guidSolutionExplorerString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSolutionExplorer = new Guid(guidSolutionExplorerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GenerateMenuGroup = 0x0001;
        public const int GenerateCommand = 0x0100;
    }
}